### ISSUE TITLE
about PSDR

### ISSUE THREAD

**Issue by GlitteringAu** [BrightGu/SingleVC#1]
Hello,I'm interested in PSDR,and where can I get the code about it?Or has it been made public?

**Comment by BrightGu** [comment]
> Hello,I'm interested in PSDR,and where can I get the code about it?Or has it been made public?

You can refer to "https://github.com/bmcfee/pyrubberband"
audio_pitch = pyrb.pitch_shift(audio, sampling_rate, shift)
The more details can access "http://www.guitarpitchshifter.com/algorithm.html"
